Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit, pull requests merged in 2021-04, with the labels that each got.

#141 fix/#137: fixed wrong week number in mensascreen
  src/components/pages/Mensascreen.js
Labels: bug

#144 refact/#106: added icons and prepared manifest.json for twa
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/maskable_icon max.png
  public/maskable_icon.png
  public/maskable_icon_x48.png
  public/maskable_icon_x72.png
Labels: refact

#142 feat/#79: added logout via drawer
  src/components/pageComponents/AppBarDrawer.js
  src/components/pages/ConditionsOfUsescreen.js
  src/components/pages/Detailscreen.js
  src/components/pages/Imprintscreen.js
Labels: feat

#145 Feat/#130 user management
  src/components/hooks/contextProvider.js
  src/components/hooks/useAuthState.js
  src/components/navigation/ProtectedRoute.js
  src/components/pageComponents/AppBarDrawer.js
  src/components/pageComponents/ContentCard.js
  src/components/pages/Contentlistscreen.js
  src/components/pages/Detailscreen.js
  src/components/pages/Homescreen.js
  src/components/pages/Loginscreen.js
  src/components/services/authService.js
  src/components/services/contentProvider.js
  src/components/services/firebaseProvider.js
  src/components/services/userProvider.js
  src/components/services/userService.js
  src/tests/pages/Loginscreen.test.js
  src/tests/services/authentication.test.js
Labels: feat

#149 refact/#148: remove nickname-ui
  src/components/pages/Homescreen.js
  src/components/pages/Settingsscreen.js
Labels: refact

#147 Feat/#60 add upload screen
  src/App.js
  src/components/pageComponents/Audiodetail.js
  src/components/pageComponents/TextDetail.js
  src/components/services/contentProvider.js
  src/components/services/firebaseProvider.js
  src/components/upload/SubcategoryList.js
  src/components/upload/Uploadscreen.js
  src/components/upload/UploadscreenContent.js
Labels: feat

#155 refact/#154: remove ui for sorting content
  src/components/pages/Contentlistscreen.js
Labels: refact

#158 refact/#157: removed unused constants
  src/components/pageComponents/AppBarDrawer.js
  src/constants/constants.js
  src/constants/testContent.js
Labels: refact

#159 docs/#138: added api server readme
  api/README.md
Labels: documentation

#160 docs/#138: added missing configuration property
  api/README.md
  api/api-server.config.js.sample
Labels: documentation

#163 feat/#138: fix source links
  README.md
Labels: documentation
