Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit, pull requests merged in 2021-02, with the labels that each got.

#66 Feat/#12 add text detail screen
  src/App.js
  src/components/pageComponents/TextDetail.js
  src/components/pages/Detailscreen.js
  src/constants/testContent.js
Labels: feat, layout

#69 Feat/#67 api server
  .gitignore
  api/api-server.js
  ci/ci-server.config.js
  ci/ci-server.config.js.sample
  ci/ci-server.js
  ecosystem.config.js
  package-lock.json
  package.json
  src/components/services/retrieveMensaData.js
Labels: devops, fix

#44 Feat/#2 implement tier 0 auth
  api/api-server.js
  ci/ci-server.js
  package-lock.json
  package.json
  src/App.js
  src/components/hooks/useUser.js
  src/components/navigation/Authentication.js
  src/components/navigation/ProtectedRoute.js
  src/components/pages/Loginscreen.js
  src/components/services/authentication.js
  src/components/services/firebase-init.js
  src/constants/firebase.config.js
  src/tests/pages/Loginscreen.test.js
Labels: feat

#77 refact/#73: added redirct to previous page
  src/components/pages/Loginscreen.js
Labels: refact

#83 Feat/#82: Feedback and Imprint screen
  .gitignore
  api/api-server.config.js.sample
  api/api-server.js
  package-lock.json
  package.json
  src/App.js
  src/components/pageComponents/CostumSnackbar.js
  src/components/pages/Feedbackscreen.js
  src/components/pages/Imprintscreen.js
Labels: feat

#91 refact/#70: removed bottom nav in contentlist
  src/components/pages/Contentlistscreen.js
Labels: refact

#93 feat/#92: implemented day recognition for mensascreen
  src/components/pages/Mensascreen.js
Labels: feat

#90 Feat/#88: Tests for feedback functionality
  package-lock.json
  package.json
  src/components/pageComponents/CustomSnackbar.js
  src/components/pages/Feedbackscreen.js
  src/components/services/sendFeedback.js
  src/tests/pageComponents/CostumSnackbar.test.js
  src/tests/pages/Feedbackscreen.test.js
  src/tests/services/sendFeedback.test.js
Labels: feat

#94 feat/#89: Added tests for authentication service
  src/components/services/authentication.js
  src/tests/services/authentication.test.js
Labels: feat

#95 feat/#76: update readme
  README.md
Labels: documentation

#97 Feat/#71: login screen usability
  src/App.js
  src/assets/images/ur-logo-bildmarke-grau.jpg
  src/components/pageComponents/CustomSnackbar.js
  src/components/pages/Detailscreen.js
  src/components/pages/Feedbackscreen.js
  src/components/pages/Loginscreen.js
  src/tests/pageComponents/CostumSnackbar.test.js
  src/tests/pageComponents/CustomSnackbar.test.js
  src/tests/pages/Feedbackscreen.test.js
Labels: feat
