Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit, pull requests merged in 2021-03, with the labels that each got.

#100 feat/#75: added welcome + info message
  src/components/pageComponents/InfoMessageCard.js
  src/components/pages/Homescreen.js
Labels: feat

#104 Feat/#62 add auth persitence levels
  src/App.test.js
  src/components/pages/Loginscreen.js
  src/components/services/authentication.js
  src/components/services/firebase-init.js
  src/tests/services/authentication.test.js
Labels: feat

#109 Feat/#86 add settings screen
  src/App.js
  src/components/pages/Settingsscreen.js
Labels: feat, layout

#110 refact/#108: content card
  src/components/pageComponents/ContentCard.js
  src/components/pageComponents/InfoMessageCard.js
  src/components/pageComponents/TopAppBar.js
  src/components/pages/Contentlistscreen.js
  src/components/pages/Homescreen.js
  src/index.css
Labels: refact

#111 feat/#28: added a color theme and used it
  src/components/pageComponents/AppBarDrawer.js
  src/components/pageComponents/Audiodetail.js
  src/components/pageComponents/ContentCard.js
  src/components/pageComponents/CustomSnackbar.js
  src/components/pageComponents/ExpandableListItem.js
  src/components/pageComponents/InfoMessageCard.js
  src/components/pageComponents/MensaCardItem.js
  src/components/pageComponents/TextDetail.js
  src/components/pageComponents/TopAppBar.js
  src/components/pageComponents/Videodetail.js
  src/components/pages/CategoryList.js
  src/components/pages/Contentlistscreen.js
  src/components/pages/Detailscreen.js
  src/components/pages/Feedbackscreen.js
  src/components/pages/Homescreen.js
  src/components/pages/Imprintscreen.js
  src/components/pages/Loginscreen.js
  src/components/pages/Mensascreen.js
  src/index.js
Labels: feat, layout

#120 feat/#116: load imprint from file
  package-lock.json
  package.json
  src/assets/textfiles/conditions-of-use.md
  src/assets/textfiles/imprint.md
  src/components/pages/Imprintscreen.js
Labels: feat

#123 feat/#114: added maskable icon to manifest
  public/manifest.json
Labels: feat

#124 fix/#59: removed second outer grid in app drawer to fix item placement
  src/components/pageComponents/AppBarDrawer.js
Labels: bug

#125 Feat/#122 integrated the remaining database fetches
  src/App.js
  src/components/hooks/contextProvider.js
  src/components/hooks/useStructure.js
  src/components/navigation/UrlParamsHelper.js
  src/components/pageComponents/Audiodetail.js
  src/components/pageComponents/Videodetail.js
  src/components/pages/CategoryList.js
  src/components/pages/Contentlistscreen.js
  src/components/pages/Detailscreen.js
Labels: feat

#121 feat/#117: add conditions of use to login screen
  src/App.js
  src/assets/images/URFitLogo.png
  src/assets/images/ur-logo-bildmarke-grau.jpg
  src/assets/textfiles/conditions-of-use.md
  src/components/pages/ConditionsOfUsescreen.js
  src/components/pages/Loginscreen.js
Labels: feat

#127 feat/#2: changed auth proxy to use uni ldap server
  api/api-server.js
Labels: feat

#129 refact/#128: changed home to heart ("Meine Seite")
  src/components/pageComponents/TopAppBar.js
  src/constants/constants.js
Labels: refact

#139 refact/#135: detailscreen layout
  src/components/pageComponents/Audiodetail.js
  src/components/pageComponents/TextDetail.js
  src/components/pageComponents/TopAppBar.js
  src/components/pageComponents/Videodetail.js
  src/components/pages/CategoryList.js
  src/components/pages/ConditionsOfUsescreen.js
  src/components/pages/Contentlistscreen.js
  src/components/pages/Detailscreen.js
  src/components/pages/Feedbackscreen.js
  src/components/pages/Imprintscreen.js
  src/components/pages/Mensascreen.js
  src/components/pages/Settingsscreen.js
Labels: refact

#140 refact/#132: categorylist info icon
  src/components/pageComponents/ExpandableListItem.js
  src/components/pages/CategoryList.js
Labels: refact
